name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install \
            pytest \
            respx \
            httpx==0.27.0 \
            fastapi==0.115.0 \
            black \
            ruff

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest
